rollback nomad to 1.11.1 and update versions

diff --git a/ansible/setup/nomad/templates/service/nomad_node_drain.sh.j2 b/ansible/setup/nomad/templates/service/nomad_node_drain.sh.j2
--- a/ansible/setup/nomad/templates/service/nomad_node_drain.sh.j2
+++ b/ansible/setup/nomad/templates/service/nomad_node_drain.sh.j2
@@ -1,3 +1,35 @@
 #!/bin/bash
+ANSIBLE_USER="{{ansible_user}}"
+FLAG_FILE="/home/${ANSIBLE_USER}/notdrain"
+NOMAD_ADDR="https://localhost:4646"
 
-if [ ! -f "/home/{{ansible_user}}/notdrain" ] ; then nomad node drain -enable -self -deadline "1h"  -m "Node shutdown" -yes -address=https://localhost:4646 -ca-cert=/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem -client-cert=/etc/opt/certs/nomad/nomad.pem -client-key=/etc/opt/certs/nomad/nomad-key.pem;fi
+# Certificates
+CA_CERT="/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem"
+CLIENT_CERT="/etc/opt/certs/nomad/nomad.pem"
+CLIENT_KEY="/etc/opt/certs/nomad/nomad-key.pem"
+
+# Main Execution
+if [[ ! -f "$FLAG_FILE" ]]; then
+    echo "Status: No exclusion file found. Starting node drain..."
+    nomad node drain \
+        -enable \
+        -self \
+        -deadline "2m" \
+        -m "Node shutdown" \
+        -yes \
+        -address="$NOMAD_ADDR" \
+        -ca-cert="$CA_CERT" \
+        -client-cert="$CLIENT_CERT" \
+        -client-key="$CLIENT_KEY"
+
+    EXIT_CODE=$?
+
+    if [ $EXIT_CODE -eq 0 ]; then
+        echo "Success: Node drain initiated successfully."
+    else
+        echo "Error: Nomad drain command failed with exit code $EXIT_CODE."
+        exit $EXIT_CODE
+    fi
+else
+    echo "Status: Exclusion file [$FLAG_FILE] exists. Skipping drain."
+fi
