Fix grpc setup

diff --git a/ansible/setup/localhost/tasks/main.yml b/ansible/setup/localhost/tasks/main.yml
--- a/ansible/setup/localhost/tasks/main.yml
+++ b/ansible/setup/localhost/tasks/main.yml
@@ -22,7 +22,7 @@
       name:
         - pexpect
         - docker
-      extra_args: --user
+      extra_args: --user --break-system-packages
 
   # Install secint on localhost
   # Need for autoconfigure consul
@@ -73,50 +73,38 @@
       dest: "/tmp/protoc"
       copy: no
 
-#  - name: "Install protoc in /usr/local/bin"
-#    register: installProto
-#    failed_when: installProto.rc != 0
-#    shell: |
-#      go install google.golang.org/protobuf/cmd/protoc-gen-go@v{{version_proto_gen}}
-#      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v{{version_proto_grpc}}
-#      go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v{{version_proto_grpc_gateway}}
-#      go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v{{version_proto_openapi}}
-#      curl -sSL "https://github.com/bufbuild/buf/releases/download/v{{version_proto_buf_cli}}/buf-$(uname -s)-$(uname -m)" -o buf
-#      sudo mv /home/{{ansible_user}}/go/bin/protoc-gen-go  /usr/local/bin
-#      sudo mv /home/{{ansible_user}}/go/bin/protoc-gen-go-grpc  /usr/local/bin
-#      sudo mv /home/{{ansible_user}}/go/bin/protoc-gen-grpc-gateway  /usr/local/bin
-#      sudo mv /home/{{ansible_user}}/go/bin/protoc-gen-openapiv2  /usr/local/bin
-#      sudo mv bin/protoc /usr/local/bin
-#      sudo mv include   /usr/local/bin/include
-#      sudo mv buf  /usr/local/bin
-#      chmod +x  /usr/local/bin/buf
-#    args:
-#      chdir: "/tmp/protoc"
-#      creates: /usr/local/bin/protoc
 
   - name: "Install protoc in /usr/local/bin"
     register: installProto
     failed_when: installProto.rc != 0
     shell: |
-      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v{{version_proto_grpc}}
-      sudo mv /home/{{ansible_user}}/go/bin/protoc-gen-go-grpc  /usr/local/bin
-      
-      go install google.golang.org/protobuf/cmd/protoc-gen-go@v{{version_proto_gen}} 
       sudo mv bin/protoc /usr/local/bin
       sudo mv include   /usr/local/bin/include
+      ret_code=$?
+      if [ $ret_code != 0 ]; then exit $ret_code; fi
       
+      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v{{version_proto_grpc}}
+      sudo mv /home/{{ansible_user}}/go/bin/protoc-gen-go-grpc  /usr/local/bin
+      ret_code=$?
+      #printf 'Error in execing gosu, %d\n' $ret_code
+      if [ $ret_code != 0 ]; then exit $ret_code; fi
+      
+      go install google.golang.org/protobuf/cmd/protoc-gen-go@v{{version_proto_gen}} 
+      sudo mv /home/{{ansible_user}}/go/bin/protoc-gen-go /usr/local/bin
+
       go install github.com/fullstorydev/grpcurl/cmd/grpcurl@v{{version_proto_grpc_curl}}
-      sudo mv grpcurl   /usr/local/bin
-      
-      go install github.com/bufbuild/buf/cmd/buf@v{{version_proto_buf_connect}}
-      sudo mv protoc-gen-connect-go   /usr/local/bin
-      
-      curl -sSL "https://github.com/bufbuild/buf/releases/download/v{{version_proto_buf_cli}}/buf-$(uname -s)-$(uname -m)" -o buf
-      sudo mv buf  /usr/local/bin
-      chmod +x  /usr/local/bin/buf
+      sudo mv /home/{{ansible_user}}/go/bin/grpcurl   /usr/local/bin
+      ret_code=$?
+      if [ $ret_code != 0 ]; then exit $ret_code; fi
+
+
     args:
       chdir: "/tmp/protoc"
       creates: /usr/local/bin/protoc
+
+  - name: "Install result protoc"
+    debug:
+      msg: "{{ installProto }}"
 
   - name: "Delete vim hcl dir  ~/.vim/pack/jvirtanen/start if present"
     when: update_vim_hcl|bool == true
